version: "3"
services:
  agdb:
    image: "postgres:13"
    container_name: "agdb"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ag-database
    ports:
      - "5432:5432" 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  ag_app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: "ag_app"
    ports:
      - "8080:8000"
    depends_on:
      - agdb


  